[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "@foundry-devops/=lib/foundry-devops/src",
]
fs_permissions = [
  { access = "read-write", path = "./" },
  { access = "read-write", path = "./script/target/" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
